"use client";

import React, { useState, useEffect, useMemo } from "react";
import { useAuth } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import { ApiClient } from "@/lib/api";
import { FileText, Download, ArrowLeft, Loader2, Calendar, Building2, X } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTranslation } from "@/hooks/useTranslation";

interface ReportData {
  _id: string;
  reportName: string;
  organizationName?: string;
  reportDate: string;
  fileName: string;
  createdAt: string;
  createdBy: {
    _id: string;
    displayName: string;
    email: string;
  };
  reportData?: {
    userSummary?: {
      totalUsers: number;
      activeUsers: number;
      avgLearningScore: number;
    };
    campaignsCount?: number;
  };
}

export default function ReportsPage() {
  const { getToken } = useAuth();
  const router = useRouter();
  const { language } = useLanguage();
  const { t, preTranslate } = useTranslation();
  const [reports, setReports] = useState<ReportData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [profile, setProfile] = useState<{ role: string } | null>(null);
  const [translationReady, setTranslationReady] = useState(false);
  const [selectedReport, setSelectedReport] = useState<ReportData | null>(null);
  const [reportUrl, setReportUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!getToken) return;

    const fetchProfile = async () => {
      try {
        const api = new ApiClient(getToken);
        const profileData = await api.getUserProfile();
        setProfile(profileData);
        
        // Only allow system_admin and client_admin
        if (profileData.role !== "system_admin" && profileData.role !== "client_admin") {
          router.push("/dashboard");
          return;
        }
      } catch (err) {
        console.error("Failed to fetch profile:", err);
        setError("Failed to verify permissions");
      }
    };

    fetchProfile();
  }, [getToken, router]);

  useEffect(() => {
    if (!getToken || !profile) return;

    const fetchReports = async () => {
      try {
        setLoading(true);
        setError(null);
        const api = new ApiClient(getToken);
        const data = await api.getUserReports();
        setReports(data.reports || []);
      } catch (err) {
        console.error("Failed to fetch reports:", err);
        setError(err instanceof Error ? err.message : "Failed to load reports");
      } finally {
        setLoading(false);
      }
    };

    fetchReports();
  }, [getToken, profile]);

  // Pre-translate static strings when language changes
  useEffect(() => {
    const preTranslatePageContent = async () => {
      if (language === "en") {
        setTranslationReady(true);
        return;
      }

      setTranslationReady(false);

      const staticStrings = [
        "Back to Dashboard",
        "My Reports",
        "report",
        "reports",
        "generated",
        "No Reports Yet",
        "Generate analytics reports from the dashboard to view them here.",
        "Go to Dashboard",
        "View",
        "Download",
        "Report Details",
        "Close",
        "Download Report",
        "Loading reports...",
        "Failed to load report. Please try again.",
        "Organization",
        "Generated on",
        "Generated by",
      ];

      try {
        await preTranslate(staticStrings);
        setTranslationReady(true);
      } catch (error) {
        console.error("Error pre-translating page content:", error);
        setTranslationReady(true);
      }
    };

    preTranslatePageContent();
  }, [language, preTranslate]);

  const handleView = async (report: ReportData) => {
    try {
      const api = new ApiClient(getToken);
      const blob = await api.downloadReport(report._id);
      
      const url = window.URL.createObjectURL(blob);
      setReportUrl(url);
      setSelectedReport(report);
    } catch (error) {
      console.error("Error loading report:", error);
      alert(t("Failed to load report. Please try again."));
    }
  };

  const handleCloseView = () => {
    if (reportUrl) {
      window.URL.revokeObjectURL(reportUrl);
      setReportUrl(null);
    }
    setSelectedReport(null);
  };

  const handleDownload = async (report: ReportData) => {
    try {
      const api = new ApiClient(getToken);
      const blob = await api.downloadReport(report._id);
      
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = report.fileName || `report-${report._id}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading report:", error);
      alert(t("Failed to download report. Please try again."));
    }
  };

  if (loading) {
    return (
      <div className="flex min-h-screen min-w-0 items-center justify-center overflow-x-hidden bg-[#f8fafc] dark:bg-[var(--navy-blue)]">
        <div className="text-center">
          <Loader2 className="w-8 h-8 animate-spin text-[var(--neon-blue)] mx-auto mb-4" />
          <p className="text-gray-600 dark:text-[var(--dashboard-text-secondary)]">{t("Loading reports...")}</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex min-h-screen min-w-0 items-center justify-center overflow-x-hidden bg-[#f8fafc] px-4 dark:bg-[var(--navy-blue)]">
        <div className="max-w-md text-center">
          <p className="mb-4 break-words text-red-600 dark:text-red-400">{error}</p>
          <button
            type="button"
            onClick={() => router.push("/dashboard")}
            className="min-h-[44px] w-full rounded-lg bg-[var(--neon-blue)] px-4 py-2 text-white hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7] sm:w-auto"
          >
            {t("Go to Dashboard")}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen min-w-0 overflow-x-hidden bg-white px-3 py-4 dark:bg-[var(--navy-blue)] sm:p-6">
      <div className="mx-auto max-w-7xl min-w-0">
        {/* Header */}
        <div className="mb-6 sm:mb-8">
          <button
            type="button"
            onClick={() => router.push("/dashboard")}
            className="mb-4 flex min-h-[44px] items-center gap-2 text-sm text-gray-600 transition-colors hover:text-[var(--neon-blue)] dark:text-[var(--dashboard-text-secondary)] dark:hover:text-[var(--neon-blue)] sm:mb-6"
          >
            <ArrowLeft className="h-4 w-4 shrink-0" />
            {t("Back to Dashboard")}
          </button>
          <div className="mb-2 flex min-w-0 items-center gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[var(--neon-blue)]/10 dark:bg-[var(--neon-blue)]/20">
              <FileText className="h-5 w-5 text-[var(--neon-blue)]" />
            </div>
            <div className="min-w-0">
              <h1 className="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">{t("My Reports")}</h1>
            </div>
          </div>
          <p className="text-sm text-gray-600 dark:text-[var(--dashboard-text-secondary)] sm:ml-[3.25rem]">
            {reports.length} {reports.length !== 1 ? t("reports") : t("report")} {t("generated")}
          </p>
        </div>

        {reports.length === 0 ? (
          <div className="rounded-lg border border-gray-200 bg-white p-6 text-center dark:border-[var(--neon-blue)]/30 dark:bg-[var(--navy-blue-light)] sm:p-12">
            <FileText className="w-12 h-12 text-gray-300 dark:text-gray-500 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">{t("No Reports Yet")}</h3>
            <p className="text-sm text-gray-600 dark:text-[var(--dashboard-text-secondary)] mb-6">
              {t("Generate analytics reports from the dashboard to view them here.")}
            </p>
            <button
              type="button"
              onClick={() => router.push("/dashboard")}
              className="min-h-[44px] w-full rounded-md bg-[var(--neon-blue)] px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7] sm:w-auto"
            >
              {t("Go to Dashboard")}
            </button>
          </div>
        ) : (
          <div className="space-y-4">
            {reports.map((report) => (
              <div
                key={report._id}
                className="overflow-hidden rounded-lg border border-gray-200 bg-white transition-all hover:border-[var(--neon-blue)]/30 dark:border-[var(--neon-blue)]/30 dark:bg-[var(--navy-blue-light)] dark:hover:border-[var(--neon-blue)]/50"
              >
                <div className="p-4 sm:p-5">
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                    <div className="flex min-w-0 flex-1 items-start gap-3 sm:gap-4">
                      <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-[var(--neon-blue)]/10 dark:bg-[var(--neon-blue)]/20">
                        <FileText className="h-6 w-6 text-[var(--neon-blue)]" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <h3 className="mb-2 break-words text-base font-semibold text-gray-900 dark:text-white">
                          {report.reportName}
                        </h3>
                        <div className="flex flex-col gap-2 text-sm text-gray-600 dark:text-[var(--dashboard-text-secondary)] sm:flex-row sm:flex-wrap sm:items-center sm:gap-4">
                          {report.organizationName && (
                            <div className="flex items-center gap-1.5">
                              <Building2 className="w-3.5 h-3.5 text-gray-400 dark:text-gray-500" />
                              <span>{report.organizationName}</span>
                            </div>
                          )}
                          <div className="flex items-center gap-1.5">
                            <Calendar className="w-3.5 h-3.5 text-gray-400 dark:text-gray-500" />
                            <span>{new Date(report.reportDate || report.createdAt).toLocaleDateString()}</span>
                          </div>
                          {report.reportData?.userSummary && (
                            <div className="flex items-center gap-1.5">
                              <span className="text-gray-400 dark:text-gray-500">•</span>
                              <span>{report.reportData.userSummary.totalUsers} users</span>
                            </div>
                          )}
                          {report.reportData?.campaignsCount !== undefined && (
                            <div className="flex items-center gap-1.5">
                              <span className="text-gray-400 dark:text-gray-500">•</span>
                              <span>{report.reportData.campaignsCount} campaigns</span>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="flex w-full shrink-0 flex-col gap-2 sm:w-auto sm:flex-row">
                      <button
                        type="button"
                        onClick={() => handleView(report)}
                        className="min-h-[44px] w-full rounded-md bg-[var(--neon-blue)] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7] sm:w-auto"
                      >
                        {t("View")}
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDownload(report)}
                        className="flex min-h-[44px] w-full items-center justify-center gap-2 rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 dark:border-[var(--neon-blue)]/30 dark:text-white dark:hover:bg-[var(--navy-blue-lighter)] sm:w-auto"
                      >
                        <Download className="h-4 w-4 shrink-0" />
                        {t("Download")}
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Report View Modal */}
        {selectedReport && reportUrl && (
          <div
            className="fixed inset-0 z-50 bg-black/50 dark:bg-black/70"
            onClick={handleCloseView}
          >
            <div
              className="flex h-[100dvh] min-h-0 w-full flex-col bg-white shadow-lg dark:bg-[var(--navy-blue-light)] sm:h-screen"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex shrink-0 items-start justify-between gap-3 border-b border-gray-200 px-3 py-3 dark:border-[var(--neon-blue)]/30 sm:items-center sm:px-6 sm:py-2">
                <h2 className="min-w-0 truncate pr-2 text-base font-semibold text-gray-900 dark:text-white sm:text-lg">{t("Report Details")}</h2>
                <button
                  type="button"
                  onClick={handleCloseView}
                  className="flex h-11 w-11 shrink-0 items-center justify-center rounded text-gray-400 transition-colors hover:text-gray-600 dark:text-gray-500 dark:hover:text-white sm:h-9 sm:w-9"
                  aria-label={t("Close")}
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
              <div className="min-h-0 flex-1 overflow-hidden">
                <iframe
                  src={reportUrl}
                  className="h-full min-h-[50dvh] w-full border-0"
                  title={selectedReport.reportName}
                />
              </div>
              <div className="flex shrink-0 flex-col gap-2 border-t border-gray-200 px-3 py-3 dark:border-[var(--neon-blue)]/30 sm:flex-row sm:justify-end sm:gap-3 sm:px-6 sm:py-2">
                <button
                  type="button"
                  onClick={handleCloseView}
                  className="min-h-[44px] w-full rounded-md border border-gray-300 px-5 py-2.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 dark:border-[var(--neon-blue)]/30 dark:text-white dark:hover:bg-[var(--navy-blue-lighter)] sm:w-auto"
                >
                  {t("Close")}
                </button>
                <button
                  type="button"
                  onClick={() => handleDownload(selectedReport)}
                  className="flex min-h-[44px] w-full items-center justify-center gap-2 rounded-md bg-[var(--neon-blue)] px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7] sm:w-auto"
                >
                  <Download className="h-4 w-4 shrink-0" />
                  {t("Download Report")}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
