"use client";

import React, { useState, useEffect, useMemo } from "react";
import { useAuth } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import { ApiClient } from "@/lib/api";
import { FileText, Download, ArrowLeft, Loader2, Calendar, Building2, X } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTranslation } from "@/hooks/useTranslation";

interface ReportData {
  _id: string;
  reportName: string;
  organizationName?: string;
  reportDate: string;
  fileName: string;
  createdAt: string;
  createdBy: {
    _id: string;
    displayName: string;
    email: string;
  };
  reportData?: {
    userSummary?: {
      totalUsers: number;
      activeUsers: number;
      avgLearningScore: number;
    };
    campaignsCount?: number;
  };
}

export default function ReportsPage() {
  const { getToken } = useAuth();
  const router = useRouter();
  const { language } = useLanguage();
  const { t, preTranslate } = useTranslation();
  const [reports, setReports] = useState<ReportData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [profile, setProfile] = useState<{ role: string } | null>(null);
  const [translationReady, setTranslationReady] = useState(false);
  const [selectedReport, setSelectedReport] = useState<ReportData | null>(null);
  const [reportUrl, setReportUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!getToken) return;

    const fetchProfile = async () => {
      try {
        const api = new ApiClient(getToken);
        const profileData = await api.getUserProfile();
        setProfile(profileData);
        
        // Only allow system_admin and client_admin
        if (profileData.role !== "system_admin" && profileData.role !== "client_admin") {
          router.push("/dashboard");
          return;
        }
      } catch (err) {
        console.error("Failed to fetch profile:", err);
        setError("Failed to verify permissions");
      }
    };

    fetchProfile();
  }, [getToken, router]);

  useEffect(() => {
    if (!getToken || !profile) return;

    const fetchReports = async () => {
      try {
        setLoading(true);
        setError(null);
        const api = new ApiClient(getToken);
        const data = await api.getUserReports();
        setReports(data.reports || []);
      } catch (err) {
        console.error("Failed to fetch reports:", err);
        setError(err instanceof Error ? err.message : "Failed to load reports");
      } finally {
        setLoading(false);
      }
    };

    fetchReports();
  }, [getToken, profile]);

  // Pre-translate static strings when language changes
  useEffect(() => {
    const preTranslatePageContent = async () => {
      if (language === "en") {
        setTranslationReady(true);
        return;
      }

      setTranslationReady(false);

      const staticStrings = [
        "Back to Dashboard",
        "My Reports",
        "report",
        "reports",
        "generated",
        "No Reports Yet",
        "Generate analytics reports from the dashboard to view them here.",
        "Go to Dashboard",
        "View",
        "Download",
        "Report Details",
        "Close",
        "Download Report",
        "Loading reports...",
        "Failed to load report. Please try again.",
        "Organization",
        "Generated on",
        "Generated by",
      ];

      try {
        await preTranslate(staticStrings);
        setTranslationReady(true);
      } catch (error) {
        console.error("Error pre-translating page content:", error);
        setTranslationReady(true);
      }
    };

    preTranslatePageContent();
  }, [language, preTranslate]);

  const handleView = async (report: ReportData) => {
    try {
      const api = new ApiClient(getToken);
      const blob = await api.downloadReport(report._id);
      
      const url = window.URL.createObjectURL(blob);
      setReportUrl(url);
      setSelectedReport(report);
    } catch (error) {
      console.error("Error loading report:", error);
      alert(t("Failed to load report. Please try again."));
    }
  };

  const handleCloseView = () => {
    if (reportUrl) {
      window.URL.revokeObjectURL(reportUrl);
      setReportUrl(null);
    }
    setSelectedReport(null);
  };

  const handleDownload = async (report: ReportData) => {
    try {
      const api = new ApiClient(getToken);
      const blob = await api.downloadReport(report._id);
      
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = report.fileName || `report-${report._id}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading report:", error);
      alert(t("Failed to download report. Please try again."));
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#f8fafc] dark:bg-[var(--navy-blue)] flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-8 h-8 animate-spin text-[var(--neon-blue)] mx-auto mb-4" />
          <p className="text-gray-600 dark:text-[var(--dashboard-text-secondary)]">{t("Loading reports...")}</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-[#f8fafc] dark:bg-[var(--navy-blue)] flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 dark:text-red-400 mb-4">{error}</p>
          <button
            onClick={() => router.push("/dashboard")}
            className="px-4 py-2 bg-[var(--neon-blue)] text-white rounded-lg hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7]"
          >
            {t("Go to Dashboard")}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white dark:bg-[var(--navy-blue)] p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <button
            onClick={() => router.push("/dashboard")}
            className="flex items-center gap-2 text-gray-600 dark:text-[var(--dashboard-text-secondary)] hover:text-[var(--neon-blue)] dark:hover:text-[var(--neon-blue)] mb-6 transition-colors text-sm"
          >
            <ArrowLeft className="w-4 h-4" />
            {t("Back to Dashboard")}
          </button>
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-lg bg-[var(--neon-blue)]/10 dark:bg-[var(--neon-blue)]/20 flex items-center justify-center">
              <FileText className="w-5 h-5 text-[var(--neon-blue)]" />
            </div>
            <div>
              <h1 className="text-2xl font-semibold text-gray-900 dark:text-white">{t("My Reports")}</h1>
            </div>
          </div>
          <p className="text-sm text-gray-600 dark:text-[var(--dashboard-text-secondary)] ml-[3.25rem]">
            {reports.length} {reports.length !== 1 ? t("reports") : t("report")} {t("generated")}
          </p>
        </div>

        {reports.length === 0 ? (
          <div className="bg-white dark:bg-[var(--navy-blue-light)] rounded-lg border border-gray-200 dark:border-[var(--neon-blue)]/30 p-12 text-center">
            <FileText className="w-12 h-12 text-gray-300 dark:text-gray-500 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">{t("No Reports Yet")}</h3>
            <p className="text-sm text-gray-600 dark:text-[var(--dashboard-text-secondary)] mb-6">
              {t("Generate analytics reports from the dashboard to view them here.")}
            </p>
            <button
              onClick={() => router.push("/dashboard")}
              className="px-5 py-2.5 bg-[var(--neon-blue)] text-white rounded-md hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7] transition-colors text-sm font-medium"
            >
              {t("Go to Dashboard")}
            </button>
          </div>
        ) : (
          <div className="space-y-4">
            {reports.map((report) => (
              <div
                key={report._id}
                className="bg-white dark:bg-[var(--navy-blue-light)] rounded-lg border border-gray-200 dark:border-[var(--neon-blue)]/30 overflow-hidden hover:border-[var(--neon-blue)]/30 dark:hover:border-[var(--neon-blue)]/50 transition-all"
              >
                <div className="p-5">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-4 flex-1">
                      <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-[var(--neon-blue)]/10 dark:bg-[var(--neon-blue)]/20 flex items-center justify-center">
                        <FileText className="w-6 h-6 text-[var(--neon-blue)]" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <h3 className="text-base font-semibold text-gray-900 dark:text-white mb-2">
                          {report.reportName}
                        </h3>
                        <div className="flex flex-wrap items-center gap-4 text-sm text-gray-600 dark:text-[var(--dashboard-text-secondary)]">
                          {report.organizationName && (
                            <div className="flex items-center gap-1.5">
                              <Building2 className="w-3.5 h-3.5 text-gray-400 dark:text-gray-500" />
                              <span>{report.organizationName}</span>
                            </div>
                          )}
                          <div className="flex items-center gap-1.5">
                            <Calendar className="w-3.5 h-3.5 text-gray-400 dark:text-gray-500" />
                            <span>{new Date(report.reportDate || report.createdAt).toLocaleDateString()}</span>
                          </div>
                          {report.reportData?.userSummary && (
                            <div className="flex items-center gap-1.5">
                              <span className="text-gray-400 dark:text-gray-500">•</span>
                              <span>{report.reportData.userSummary.totalUsers} users</span>
                            </div>
                          )}
                          {report.reportData?.campaignsCount !== undefined && (
                            <div className="flex items-center gap-1.5">
                              <span className="text-gray-400 dark:text-gray-500">•</span>
                              <span>{report.reportData.campaignsCount} campaigns</span>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="flex gap-2 flex-shrink-0">
                      <button
                        onClick={() => handleView(report)}
                        className="px-4 py-2 bg-[var(--neon-blue)] text-white rounded-md hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7] transition-colors text-sm font-medium"
                      >
                        {t("View")}
                      </button>
                      <button
                        onClick={() => handleDownload(report)}
                        className="px-4 py-2 border border-gray-300 dark:border-[var(--neon-blue)]/30 text-gray-700 dark:text-white rounded-md hover:bg-gray-50 dark:hover:bg-[var(--navy-blue-lighter)] transition-colors text-sm font-medium flex items-center gap-2"
                      >
                        <Download className="w-4 h-4" />
                        {t("Download")}
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Report View Modal */}
        {selectedReport && reportUrl && (
          <div
            className="fixed inset-0 bg-black/50 dark:bg-black/70 z-50"
            onClick={handleCloseView}
          >
            <div
              className="bg-white dark:bg-[var(--navy-blue-light)] w-full h-full flex flex-col shadow-lg"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex justify-between items-center px-6 py-2 border-b border-gray-200 dark:border-[var(--neon-blue)]/30 flex-shrink-0">
                <h2 className="text-lg font-semibold text-gray-900 dark:text-white">{t("Report Details")}</h2>
                <button
                  onClick={handleCloseView}
                  className="text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-white transition-colors p-1"
                  aria-label="Close"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
              <div className="flex-1 overflow-hidden" style={{ height: 'calc(100vh - 100px)' }}>
                <iframe
                  src={reportUrl}
                  className="w-full h-full border-0"
                  title={selectedReport.reportName}
                  style={{ height: '100%' }}
                />
              </div>
              <div className="px-6 py-2 border-t border-gray-200 dark:border-[var(--neon-blue)]/30 flex justify-end gap-3 flex-shrink-0">
                <button
                  onClick={handleCloseView}
                  className="px-5 py-2.5 border border-gray-300 dark:border-[var(--neon-blue)]/30 text-gray-700 dark:text-white rounded-md hover:bg-gray-50 dark:hover:bg-[var(--navy-blue-lighter)] transition-colors text-sm font-medium"
                >
                  {t("Close")}
                </button>
                <button
                  onClick={() => handleDownload(selectedReport)}
                  className="px-5 py-2.5 bg-[var(--neon-blue)] text-white rounded-md hover:bg-[var(--medium-blue)] dark:hover:bg-[#4fc3f7] transition-colors text-sm font-medium flex items-center gap-2"
                >
                  <Download className="w-4 h-4" />
                  {t("Download Report")}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
